name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into Remote Server and Deploy
      env:
        GIT_PAT: ${{ secrets.MY_GITHUB_PAT }}
      run: |
        echo "Starting deployment..."
        ssh -o StrictHostKeyChecking=no student@csi420-02-vm5.ucd.ie << 'EOF'
          echo "Connected to server."
          cd ~/COMP3030J-Software-Engineering-Project-2
          echo "Pulling latest code from main branch..."
          git pull https://yangyniii:${{ secrets.MY_GITHUB_PAT }}@github.com/yangyniii/COMP3030J-Software-Engineering-Project-2.git main
          echo "Activating virtual environment..."
          source ~/venv/bin/activate
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Reloading Gunicorn..."
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          echo "Deployment complete."
        EOF
