name: Server Configuration and Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH and Configure Server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 137.43.49.54 >> ~/.ssh/known_hosts
        
        ssh student@csi420-02-vm5.ucd.ie << 'EOF'
          # Clone Repository
          git clone https://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@github.com/username/repository.git website || true
          cd website

          # Setup Virtual Environment and Install Requirements
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Install Gunicorn
          pip install gunicorn

          # Install and Configure Nginx
          sudo apt update
          sudo apt install -y nginx

          sudo bash -c 'cat > /etc/nginx/sites-available/csi420-02-vm5.ucd.ie << "NGINX_CONF"
          upstream app_server {
              server unix:/run/gunicorn.sock;
          }
          
          server {
              listen 80;
              server_name csi420-02-vm5.ucd.ie;

              location / {
                  proxy_pass http://app_server;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }
          NGINX_CONF'

          sudo ln -s /etc/nginx/sites-available/csi420-02-vm5.ucd.ie /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx

          # Configure Gunicorn and Systemd
          cat > gunicorn.conf.py << "EOF"
          import multiprocessing

          bind = "127.0.0.1:5000"
          workers = multiprocessing.cpu_count() * 2 + 1
          EOF

          sudo bash -c 'cat > /etc/systemd/system/gunicorn.service << "SYSTEMD_CONF"
          [Unit]
          Description=gunicorn daemon
          After=network.target

          [Service]
          User=student
          Group=student
          WorkingDirectory=/home/student/website
          ExecStart=/home/student/website/venv/bin/gunicorn --config gunicorn.conf.py hello:app

          [Install]
          WantedBy=multi-user.target
          SYSTEMD_CONF'

          sudo systemctl daemon-reload
          sudo systemctl enable --now gunicorn

          echo "Deployment completed successfully!"
        EOF
