name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_USERNAME: yangyniii
        GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no student@csi420-02-vm5.ucd.ie << 'EOF'
          echo "Connected to server."
          cd ~/COMP3030J-Software-Engineering-Project-2
          echo "Pulling latest code from main branch with authentication..."
          git pull origin main
          echo "Activating virtual environment..."
          source ~/venv/bin/activate
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Reloading Gunicorn..."
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl reload gunicorn
          echo "Deployment complete."
        EOF

